### ISSUE TITLE
Off by one error in render_stride

### ISSUE THREAD

**Issue by NthStarFarer** [4gboframram/onna#3]
The move cursor escape code used in render_stride uses one-indexed values for the row and column, but the values passed are zero indexed. This results in a row and column of pixels and the bottom and right edges of the video to only be set once when the first frame is drawn, since that is the only time a whole frame is normally drawn without moving the cursor. This was likely missed due to both Bad Apple and I wanna be a girl starting on pure black frames, meaning that this only caused a black border.
This also seems to be the cause of at least some of the artifacting  I mentioned in #1.

This can be seen as the white border around the bottom and right sides in [this](https://www.youtube.com/watch?v=5XAd4aGv52M) video

**Comment by lilyyy411** [comment]
Yep, I noticed this a while ago. I forgot that the terminal's escape sequences were 1-indexed. The next update will fix it because it will use crossterm
